### ISSUE TITLE
Doesn't work in router.replace

### ISSUE THREAD

**Issue by Sofrosine** [ndungtse/next13-progressbar#10]
**Describe the bug**
I'm trying to use router.replace and the loading doesn't appear. 
It works well when using router.push 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ndungtse** [comment]
Issue now fixed in `v1.1.2`. Thanks in advance @Sofrosine
