### ISSUE TITLE
i want to make the animation goes from right to left 

### ISSUE THREAD

**Issue by chrhi** [ndungtse/next13-progressbar#21]
hi , 
i wonder if i can make the animation when changing the the page goes from right to left 
thank you

**Comment by ndungtse** [comment]
@chrhi, I think that animation has nothing to require this package. But if you want to make page transitions you can use other techniques but not this package. For implementation of page transitions in next.js maybe you can check this [blog](https://blog.logrocket.com/advanced-page-transitions-next-js-framer-motion/)
