### ISSUE TITLE
Missing Suspense boundary with useSearchParams

### ISSUE THREAD

**Issue by HighError** [ndungtse/next13-progressbar#24]
**Describe the bug**
[Missing Suspense boundary with useSearchParams](https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout)

**To Reproduce**
1. Add Next13ProgressBar to app
2. Build

**Expected behavior**
Build ok.

**Screenshots**
![image](https://github.com/ndungtse/next13-progressbar/assets/46526245/5b8a35aa-9711-4f20-aa57-b8c9fc142272)

**Additional context**
You need to wrap the component in Suspend. I think it's worth adding this to the library so that the developer doesn't have to think about it.
![image](https://github.com/ndungtse/next13-progressbar/assets/46526245/fe810cdc-5fa8-43c0-a17c-c823a14b3786)

**Comment by ndungtse** [comment]
This issue is the same as #18 which I moved into discussion if the feature can be added but it looks like it might be helpful to be included in package. I'll try to include it in the next versions. Thanks in advance @HighError .

**Comment by MrLoh** [comment]
Just wasted 4 hours tracking this down.
