### ISSUE TITLE
<Next13ProgressBar />can be used directly in loading.tsx, utilizing Nextjs 13's Suspense boundaries. 

### ISSUE THREAD

**Issue by Nirmal314** [ndungtse/next13-progressbar#27]
There is no problem in creating Provider and using it in layout.tsx file but it can also be used in loading.tsx file directly (in server/client components), it is much simpler and easier. Also it utilities the power of Nextjs 13's Suspense boundaries.

**Comment by ndungtse** [comment]
@Nirmal314 I get that it can be used there but the progressbar is also show on query param change which Nextjs 13's Suspense can't treat as loading. So we have to sticky on this implementation to ensure consistency as maybe there will be change in api of nextjs which even change the need of loading.tsx 🤷🏻‍♂️

**Comment by Nirmal314** [comment]
That makes sense. @ndungtse
