### ISSUE TITLE
Ctrl + click to open link in new tab make current tab show loading forever

### ISSUE THREAD

**Issue by quanhv94** [ndungtse/next13-progressbar#6]
**Describe the bug**
When open a link in new tab using ctrl + click, loading animation is displayed forever.

**To Reproduce**
Click a next link with ctrl press

**Expected behavior**
Do not show loading animation

**Comment by ndungtse** [comment]
Thanks for reporting this. Of course the loading bar shouldn't appear as ctrl + click opens new tab and this is going to be fixed soon. Hopefully the next release will fix it

**Comment by ndungtse** [comment]
Its now fixed with latest version ```1.1.0```

**Comment by quanhv94** [comment]
@ndungtse Could you update more on this issue.  Press Alt key + click link (option key + click on MacOS) cause the same issue.
