### ISSUE TITLE
Loading forever on Alt+click to download a link

### ISSUE THREAD

**Issue by quanhv94** [ndungtse/next13-progressbar#7]
Thank you so much for previous fix on ctrl+click issue. But I found another similar one.

Describe the bug
When click a link with alt key (option key on MacOS), loading animation is displayed forever also.

To Reproduce
Click a next link with alt key press

Expected behavior
Do not show loading animation

**Comment by ndungtse** [comment]
Thanks again, I think I have to make it not load as I previously did

**Comment by ndungtse** [comment]
Issue fixed in version `1.1.1`
