### ISSUE TITLE
Next13-progressbar causing hydration issues

### ISSUE THREAD

**Issue by Ninjagor** [ndungtse/next13-progressbar#9]
**Describe the bug**
Bug is found when I added this to my providers.tsx (along with redux) and hydration errors occur.

**To Reproduce**
1. Create providers.tsx
2. Paste in the provided code (whatever was in documentation + my redux provider code):

```typescript
"use client";

import { store } from "./store";
import { Provider } from "react-redux";

import { Next13ProgressBar } from 'next13-progressbar';

export function Providers({ children }: { children: React.ReactNode }) {
  return (
  <Provider store={store}>
    {children}
    <Next13ProgressBar height="4px" color="#DE2f2f" options={{ showSpinner: true }} showOnShallow />
  </Provider>
  )
}
```

**Expected behavior**
I expected it to work (which is does) but I did not expect hydration errors.

**Screenshots**
No screenshots but here is my error msg:
```
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <style> in <body>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Chrome Version 120.0.6099.109 (Official Build) (arm64)

**Smartphone (please complete the following information):**
N/A (using macbook)

**Additional context**
Error is dismissible but I do not like the hydration error there, as it could cause complications in the future. Idk if its a problem with my code structuring or with the lib.

**Comment by Ninjagor** [comment]
Putting it outside the redux provided <Provider> tag also does not work btw

**Comment by Ninjagor** [comment]
Nvm, i found the issue. I had nested layout.tsx files, and I put the provider in the root one. That caused the errors. I will be restructuring my project to fix this

**Comment by Ninjagor** [comment]
Yep, issue was with my code. I structured my code in a way where new body's were being mounted improperly. I will be removing the <body> tags in my nested layouts to fix this issue.

**Comment by ndungtse** [comment]
Okay. Thanks for clarifying
